### ISSUE TITLE
[Queation] todo-axum compiler error

### ISSUE THREAD

**Issue by hellojaewon** [rstropek/rust-api-fxs#1]
Hi, rainer.
When I clone this repository and try to run todo-axum, there was an error in [todo-axum/src/main.rs#51](https://github.com/rstropek/rust-api-fxs/blob/main/todo-axum/src/main.rs#L51) as follows,
*E: no method named 'into_make_service' found for struct 'Router<Arc<tokio::sync::RwLock<TodoStore>>, _>' in the current scope*

I watched [Eurorust 2022: Building Web APIs with Rust - State of the Union](https://youtu.be/H6-cZuU0DtI?t=3081).
The difference was the type of [app](https://github.com/rstropek/rust-api-fxs/blob/main/todo-axum/src/main.rs#L38).

In my environment
`Router<Arc<RwLock<TodoStore>>, _>`

yours
`Router<Arc<RwLock<TodoStore>>>`

I tried to solve this problem with my own.
My guess is that, according to the [axum/routing/mod.rs#538-542](https://docs.rs/axum/latest/src/axum/routing/mod.rs.html#538-542), the two functions, into_make_service and into_make_service_with_connect_info, can be used that satisfy the bound
`impl<B> Router<(), B>
where
    B: HttpBody + Send + 'static,`

However, I can't figure out why this happens and how to resolve them.

Anyway, I'm new to rust programming language and I just fall in love in rust like you.
Your presentation help me learn rust but also the passion on programming as well.
Thank you.

**Comment by rstropek** [comment]
Hi @hellojaewon! Some changes in Axum 0.6 broke my code as it was originally developed with a release candidate version. Today, I took the time to update all samples. I also updated some deprecated functions regarding base64 encoding and some necessary, functional changes to the Spin variant. Now everything should be up to date. Hope that helps.
